onemodel/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'onemodel'

urlpatterns = [
    path('', views.index, name='index'),
    path('add/', views.add, name='add'),
    path('<int:post_id>/post_detail', views.post_detail, name='post_detail'),
    path('admin/', admin.site.urls),
]

simple/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('onemodel/', include('onemodel.urls')),
    path('admin/', admin.site.urls),
]

onemodel/models.py
from django.db import models


class Post(models.Model):
    title = models.CharField(max_length=30)
    body = models.TextField(max_length=500)

    def __str__(self):
        return self.title

onemodel/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        exclude = ()

onemodel/views.py
from django.shortcuts import render, HttpResponseRedirect, reverse
from .models import Post
from django.utils import timezone
from .forms import PostForm



# Create your views here.

def index(request):
    tasks = Post.objects.all()
    return render(request, 'onemodel/index.html', {'tasks': tasks})


def add(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.save()
            return HttpResponseRedirect(reverse('onemodel:index'))
    else:
        form = PostForm()
        return render(request, 'onemodel/add.html', { 'form': form })


def post_detail(request, post_id):
    
    post = Post.objects(Post, pk=post_id)
    return render(request, 'detail.html', {'post': post})

onemodel/templates/onemodel/add.html
<h1>Add Post Form </h1>
<form action="{% url 'onemodel:add' %}" method="post">
    <table>
 {% csrf_token %}
 {{ form }}
    </table>
    <input type="submit" value="Submit">

</form>

onemodel/templates/onemodel/index.html
<textarea onclick="this.focus();this.select()" style="width: 100%;"> {% filter force_escape %} {% debug %} {% endfilter %}</textarea>

<h1>Post Model</h1>
{% if tasks %}
<table>
    {% for task in tasks %}
    <tr>
        <td><a href="post_detail/{{task.id}}">View Detail</a></td>
        <td>{{ task.title}}</td>
        <td>{{ task.body}}</td>
    </tr>
    {% endfor %}
</table>
<a href="/onemodel/add/">Click Here to add one!</a>
{% else %}
<p>No Posts have been made yet! <a href="/onemodel/add/">Click Here to add one!</a> </p>
{% endif %}

onemodel/templates/onemodel/thanks.html
<p>Thanks.</p>